parameters:
    rl_dart_routing.routes_extractor.class: RL\DartRoutingBundle\Service\RoutesExtractor

services:
    rl_dart_routing.routes_extractor:
        class: %rl_dart_routing.routes_extractor.class%
        arguments: [@router]
